if(getState("STATE_PAUSED")) {
    
    instance_destroy(ui);
    ui = noone;
    removeState("STATE_PAUSED");
    removeState("STATE_FROZEN");
    
} else {
    
ui = instance_create_layer(0, 0, "Instances", ObjectElementUI)
    .setWidth("3in")
    .setHeight("3in")
    .centerX()
    .setY("1hin")
    .createNewChild(ObjectArrayButtonContainer)
        .createNewChild(ObjectButton)
            .setWidth("2in")
            .setHeight("1cm")
            .centerX()
            .setY("1hin")
            .setCallback(UIScriptResume)
            .createNewChild(ObjectText)
                .setText("Resume")
                .setFontSize(2.0)
                .centerX()
                .centerY()
                .fixTextAlign()
                .getParent().getParent()
        .createNewChild(ObjectButton)
            .setWidth("2in")
            .setHeight("1cm")
            .centerX()
            .setY("2hin")
            .setCallback(UIScriptCatnap)
            .createNewChild(ObjectText)
                .setText("Save and Rest")
                .setFontSize(2.0)
                .centerX()
                .centerY()
                .fixTextAlign()
                .getParent().getParent()
        .createNewChild(ObjectButton)
            .setWidth("2in")
            .setHeight("1cm")
            .centerX()
            .setY("3hin")
            .setCallback(UIScriptQuit)
            .createNewChild(ObjectText)
                .setText("Quit")
                .setFontSize(2.0)
                .centerX()
                .centerY()
                .fixTextAlign()
                .getHead()
    .createNewChild(ObjectElementUI)
        .setWidth("5in")
        .setHeight("3in")
        .centerX()
        .setY("7hin")
        .createNewChild(ObjectText)
            .setText("WASD/Arrow Keys - Move")
            .setFontSize(3.0)
            .centerX()
            .fixTextAlign()
            .setY("1hin")
            .setFontSize(3.0)
            .getParent()
        .createNewChild(ObjectText)
            .setText("Z/Space Bar - Attack")
            .setFontSize(3.0)
            .centerX()
            .fixTextAlign()
            .setY("1in")
            .getParent()
        .createNewChild(ObjectText)
            .setText("Shift Key - Dash")
            .setFontSize(3.0)
            .centerX()
            .fixTextAlign()
            .setY("3hin")
            .getParent()
        .createNewChild(ObjectText)
            .setText("E Key - Interact")
            .setFontSize(3.0)
            .centerX()
            .fixTextAlign()
            .setY("2in")
            .getHead();
    
    setState("STATE_PAUSED");
    setState("STATE_FROZEN");
}